config/routes.rb
Rails.application.routes.draw do

  get 'googlebooks/show'

  get '/about' => 'annexes#about', as: :About
  get '/documentation' => 'annexes#documentation', as: :Documentation
  get '/contact' => 'annexes#contact', as: :Contact
  
  root 'welcome#index'
  get '/home' => 'welcome#home', as: :Home

  resources :password_resets, except: [:index, :destroy]
  resources :confirmations, only: :show
  resources :sessions, only: [:create, :destroy]
  
  resources :users, except: [:new, :show, :destroy, :edit, :index] do
    resources :books, except: [:index]
  end

  get '/singup' => 'users#new', as: :Singup
  get '/login' => 'sessions#new', as: :Login

  get 'users/:username' => 'users#show'
  put 'users/:username' => 'users#update'
  delete 'users/:username' => 'users#destroy'
  get 'users/:username/edit' => 'users#edit'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # External resources definitions
  authenticates_with_sorcery!
  has_many :books

  obfuscate_id
  
  # Virtual Attributes
  attr_accessor :password, :password_confirmation

  # Validations
  validates :username, :email, :password, presence: true, on: :create
  validates :username, uniqueness: true
  validates :email, uniqueness: true, format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\z/, message: "must be a valid email" }

  validates :password, length: { minimum: 3 }, on: :create
  validates :password, confirmation: true, on: :create

  has_attached_file :avatar,
    storage: :dropbox,
    styles: { medium: "300x300!", thumb: "100x100!", icon: "50x50!" },
    default_url: "https://en.opensuse.org/images/0/0b/Icon-user.png",
    dropbox_credentials: Rails.root.join("#{Rails.root}/config/dropbox.yml"),
    dropbox_options: { path: proc { |style| "files/avatars/#{id}/#{avatar.original_filename}" } },
    unique_filename: true 
  validates_attachment_content_type :avatar, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  # Callbacks
  before_save :format_attributes

  # Methods
  private
  def format_attributes
    self.email.downcase!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :show]
  before_action :get_user, only: [:show, :edit, :update]
  before_filter :require_login, :only => [:edit, :update, :destroy]

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    current_user.assign_attributes(update_user_params)
    if current_user.save
      redirect_to "/users/#{current_user.username}"
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to :root, notice: 'Tu proceso de registro esta casi completado, ve a tu badeja de entrada para completarlo'
    else
      flash[:error] = 'Tu proceso de registro no pudo ser completado'
      render :new
    end
  end

  def destroy
    current_user.destroy
    logout unless destroyed?
    redirect_to :root
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def update_user_params
    params.require(:user).permit(:avatar, :username, :email, :firstname, :lastname, :biography, :location, :password, :password_confirmation)
  end

  def get_user
    @user = User.find_by_username(params[:username])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div id="background-image" style="background: url(http://p1.pichost.me/640/64/1889210.jpg) no-repeat center center; background-size: cover; -webkit-background-size: cover;-moz-background-size: cover; -o-background-size: cover;background-attachment: fixed;"></div> 
<div id="background-overlay"></div>

<div class="container">
  <h1>Editar Perfil</h1>
  <hr>
  <%= form_for current_user, html: { multipart: true, class: "form-horizontal" } do |f| %>
    <div class="row">
       <div class="col-md-3">
        <div class="text-center">
          <%= image_tag current_user.avatar.url(:thumb), class: "avatar img-circle" %>
          <h6>Sube una foto diferente...</h6>
          <%= f.file_field :avatar %>
        </div>
      </div>
      <div class="col-md-9 personal-info">
        <% if current_user.errors.any? %>
          <div class="alert alert-info alert-dismissable">
            <a class="panel-close close" data-dismiss="alert">×</a> 
            <i class="fa fa-coffee"></i>
            <ul>
              <% for message in current_user.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        
        <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Información Personal</h3>

        <div class="form-group">
          <%= f.label 'Nombre de Usuario', class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :username, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Nombre", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :firstname, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Apellido", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :lastname, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Correo Electronico", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :email, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Biografia", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_area :biography, size: "19x10", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Ubicacion", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :location, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Contraseña", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.password_field :password, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Confirmar Contraseña", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-8">
            <%= f.submit "Guardar Cambios", class: 'btn btn-primary' %>
            <span></span>
            <%= link_to "Cancelar", "/users/#{current_user.username}", class: 'btn btn-default' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div id="background-image" style="background: url(http://p1.pichost.me/640/64/1889210.jpg) no-repeat center center; background-size: cover; -webkit-background-size: cover;-moz-background-size: cover; -o-background-size: cover;"></div> 
<div id="background-overlay"></div>
<div class="main-content" style="position:relative;">
  <div class="container">
    <%= form_for @user, html: { class: "form-signin" } do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-info alert-dismissable">
          <a class="panel-close close" data-dismiss="alert">×</a> 
          <i class="fa fa-coffee"></i>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <h2 class="form-signin-heading">Registra tus datos</h2>
      
      <%= f.label :username, class: "sr-only" %>
      <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
    
      <%= f.label :email, class: "sr-only" %>
      <%= f.email_field :email, class: "form-control", placeholder: "Email" %>

      <%= f.label :password, class: "sr-only" %>
      <%= f.password_field :password, class: "form-control", placeholder: "Password" %>

      <%= f.label :password_confirmation, class: "sr-only" %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation" %>
       

      <%= f.submit "Registrarme", class: 'btn btn-lg btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div id="background-image" style="background: url(http://p1.pichost.me/640/64/1889210.jpg) no-repeat center center; background-size: cover; -webkit-background-size: cover;-moz-background-size: cover; -o-background-size: cover;background-attachment: fixed;"></div> 
<div id="background-overlay"></div>

<%= render 'shared/alerts' %>

<div class="main-content">
  <div class="container">
    <div class="info-page">
      <div class="row">
        <div class="col-lg-9 col-md-9"> 
          <h1><%= @user.username %></h1> 
        </div>
        <div class="col-lg-3 col-md-3">
          <% if current_user == @user %>
            <%= link_to 'Editar', "/users/#{@user.username}/edit", class: "btn btn-primary" %>
          <% end %> 
        </div>
      </div>

      <div class="line"></div>

      <div class="row">
        <div class="col-lg-2 col-md-4 col-sm-12 col-xs-12"> 
          <%= image_tag @user.avatar.url(:medium), class: "profile-img img-responsive img-circle" %>
        </div>

        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12"> 
          <h2>Biografía</h2>
          <div id="user-biography"><%= @user.biography %></div>
        </div>
        <div class="col-lg-5 col-md-4 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1"> 
          <h2>Estadísticas</h2>
          <div class="profile-container">
            <p> <span>ID de usuario: </span> <%= (@user.id * 12345).to_s(16) %></p> 
            <p> <span>Se unió: </span> <%= time_ago_in_words(@user.created_at) %></p> 
            <p> <span>Ultima visita: </span> <%= time_ago_in_words(@user.last_login_at) %></p>
            <p> <span>Libros creados: </span> <%= @user.books.size %></p> 
            <p> <span>ip ultima conexion: </span> <%= @user.last_login_from_ip_address %> </p>
          </div> 
        </div>
      </div>

      <div class="line"></div>

      <div class="row">
        <div class="col-lg-9 col-md-9"> 
          <% if current_user == @user %> 
            <h3>Mis Libros</h3>
          <% else %>
            <h3>Libros</h3>
          <% end %> 
        </div>
        <div class="col-lg-3 col-md-3">
          <%= link_to 'Crear Libro', new_user_book_path(@user), class: 'btn btn-primary crtbook' %> 
        </div>
      </div>

      <div class="line"></div>

      <div class="row"> 
        <div class="col-xs-20"> 
          <div class="row-fluid recent-downloads">
            <% @user.books.each do |book| %> 
              <div class="col-xs-6 col-sm-6 col-md-2 col-lg-2 rbook">
                <h4><%= book.title %></h4>
                <%= link_to user_book_path(@user, book) do %>
                  <%= image_tag book.image(:thumb) %>
                <% end %>
              </div>
            <% end %>  
          </div> 
        </div> 
      </div>
    </div>
  </div>
</div>