config/routes.rb
Rails.application.routes.draw do

  get 'googlebooks/show'

  get '/about' => 'annexes#about', as: :About
  get '/documentation' => 'annexes#documentation', as: :Documentation
  get '/contact' => 'annexes#contact', as: :Contact
  
  root 'welcome#index'
  get '/home' => 'welcome#home', as: :Home

  resources :password_resets, except: [:index, :destroy]
  resources :confirmations, only: :show
  resources :sessions, only: [:create, :destroy]
  
  resources :users, except: [:new, :show, :destroy, :edit, :index] do
    resources :books, except: [:index]
  end

  get '/singup' => 'users#new', as: :Singup
  get '/login' => 'sessions#new', as: :Login

  get 'users/:username' => 'users#show'
  put 'users/:username' => 'users#update'
  delete 'users/:username' => 'users#destroy'
  get 'users/:username/edit' => 'users#edit'
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :require_login, only: :home 

  def index
    key = 'AIzaSyDLYwW6jCVe15VBbsFFZhZ_INZNgol-oUs'
    user_ip = request.remote_ip
    redirect_to :Home if current_user
    if params[:search]
      if params[:search] != ''
        ebooks = Book.search('title', params[:search]).to_a
        gbooks = GoogleBooks.search(params[:search], {count: 30, api_key: key}, user_ip).to_a
        @books = (ebooks + gbooks).paginate(page: params[:page], per_page: 5)
      else
        # @best_book = Scraping.scrap
        @books = []
      end
    else
      # @best_book = Scraping.scrap
      @books = []
    end
  end

  def home
    key = 'AIzaSyDLYwW6jCVe15VBbsFFZhZ_INZNgol-oUs'
    user_ip = request.remote_ip
    @filters = ['no filter', 'partial', 'full', 'free-ebooks', 'paid-ebooks', 'ebooks']
    @keywords = ['no keyword', 'title', 'authors', 'publisher', 'isbn']
    if params[:search]
      if params[:search] != ''
        if params[:filtering] == 'no filter'
          if params[:keyword] == 'no keyword'
            ebooks = Book.search('title', params[:search]).to_a
            gbooks = GoogleBooks.search(params[:search], {count: 30, api_key: key}, user_ip).to_a
            @books = (ebooks + gbooks).paginate(page: params[:page], per_page: 5)
          else
            ebooks = Book.search(params[:keyword], params[:search]).to_a
            gbooks = GoogleBooks.search(params[:search], {count: 30, api_key: key}, user_ip).to_a
            @books = (ebooks + gbooks).paginate(page: params[:page], per_page: 5)
          end
        else
          if params[:keyword] == 'no keyword'
            if params[:filtering] == 'ebooks' or params[:filtering] == 'free-ebooks'
              ebooks = Book.search('title', params[:search]).to_a
              gbooks = GoogleBooks.search(params[:search], {filter: params[:filtering], count: 30, api_key: key}, user_ip).to_a
              @books = (ebooks + gbooks).paginate(page: params[:page], per_page: 5)
            else
              @books = GoogleBooks.search(params[:search], {filter: params[:filtering], count: 30, api_key: key}, user_ip).to_a.paginate(page: params[:page], per_page: 5)
            end
          else
            if params[:filtering] == 'ebooks' or params[:filtering] == 'free-ebooks'
              ebooks = Book.search(params[:keyword], params[:search]).to_a
              gbooks = GoogleBooks.search("#{params[:keyword]}:#{params[:search]}", {filter: params[:filtering], count: 30, api_key: key}, user_ip).to_a
              @books = (ebooks + gbooks).paginate(page: params[:page], per_page: 5)
            elsif params[:filtering] == nil
              ebooks = Book.search('title', params[:search]).to_a
              gbooks = GoogleBooks.search(params[:search], {count: 30, api_key: key}, user_ip).to_a
              @books = (ebooks + gbooks).paginate(page: params[:page], per_page: 5)
            else
              @books = GoogleBooks.search("#{params[:keyword]}:#{params[:search]}", {filter: params[:filtering], count: 30, api_key: key}, user_ip).to_a.paginate(page: params[:page], per_page: 5)
            end
          end
        end
      else
        @books = []
      end
    else
      @books = []
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def in_group_of_three(books)
    books.each_slice(3).to_a
  end

end

app/views/welcome/_show_results.html.erb
<div id="results-frame" class="container" style="position:relative;">
  <div class="row">
    <% @books.each do |book| %> 
        <div class="book-result col-md-15 col-lg-15 col-sm-6 col-xs-6">
          <div class="result-container">
            <figure>
              <% if book.methods.include?(:user) %>
                <% if book.image %>
                  <%= link_to user_book_path(book.user, book), target: "_blank" do %>
                    <%= image_tag book.image(:thumb), class: "thumbnail", size: '180x265' %>
                  <% end %>
                <% else %>
                  <%= link_to user_book_path(book.user, book), target: "_blank" do %>
                    <%= image_tag 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSo8uPVFZTL8nxsBIPhyBw9DxZ0lbyS4hqMpQxQU4wYu0gaFDe34q-UhsHr', class: "thumbnail", size: '180x265' %>
                  <% end %>
                <% end %>
              <% else %>
                <% if book.image_link %>
                  <%= link_to googlebooks_show_path(isbn: book.isbn, title: book.title), target: "_blank" do %>
                    <%= image_tag book.image_link(zoom: 2), class: "thumbnail", size: '180x265' %>
                  <% end %>
                <% else %>
                  <%= link_to googlebooks_show_path(isbn: book.isbn, title: book.title), target: "_blank" do %>
                    <%= image_tag 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSo8uPVFZTL8nxsBIPhyBw9DxZ0lbyS4hqMpQxQU4wYu0gaFDe34q-UhsHr', class: "thumbnail", size: '180x265' %>
                  <% end %>
                <% end %>
              <% end %>
            </figure>
            <div class="book-result-bottom">
              <% if book.methods.include?(:user) %>
                <%= link_to book.title, user_book_path(book.user, book), class: "book-title", target: "_blank" %>
                <div class="book-year"><%= book.published_date %></div>
              <% else %>
                <%= link_to book.title, googlebooks_show_path(isbn: book.isbn, title: book.title), class: "book-title", target: "_blank" %>
                <div class="book-year"><%= book.published_date %></div>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
  <center><%= will_paginate @books, renderer: BootstrapPagination::Rails, inner_window: 1, outer_window: 0  %></center>
</div>

app/views/welcome/home.html.erb
<div id="background-image" style="background: url(http://p1.pichost.me/640/64/1889210.jpg) no-repeat center center; background-size: cover; -webkit-background-size: cover;-moz-background-size: cover; -o-background-size: cover;background-attachment: fixed;"></div> 
<div id="background-overlay"></div>

<div class="container-fluid collapse navbar-collapse" style="position:relative;background:#292c2f;" id="search-book-div">
  <%= form_tag(:Home, :method => "get", id: "search-form-home") do %>
    <div class="container" style="margin-top:10;margin-bottom:10px;">
      <div class="row">
        <%= render 'shared/alerts' %>
        <div class="col-md-12 col-sm-12 col-xs-12">
          <p class="term">Término de Busqueda:</p>
          <div class="input-group" style="width:100%;margin-bottom:5px;">
            <%= text_field_tag :search, params[:search], class: "form-control", style: "height:34px;", placeholder: "Busca un libro" %>
            <span class="input-group-btn">
              <%= submit_tag "Buscar", :name => nil, class: 'btn btn-primary' %>
            </span>           
          </div>
        </div>
      </div>
      <div class="row" id="filters">
        <div class="col-md-3 col-sm-6 col-xs-6">
          <p>Palabra Clave</p>
          <%= select_tag :keyword, options_for_select(@keywords), class: "form-control" %>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-6">
          <p>Filtro</p>
          <%= select_tag :filtering, options_for_select(@filters), class: "form-control" %>
        </div>
      </div>
    </div>
  <% end %>
</div>



<% if @books == [] %>
  <div class="container" style="position:relative;">
    <h1 id="results-h">Mis Libros</h1>
  </div>
  <div class="line"></div>

  <div class="row"> 
    <div class="col-xs-20"> 
      <div class="row-fluid recent-downloads">
        <% current_user.books.each do |book| %> 
          <div class="col-xs-6 col-sm-6 col-md-2 col-lg-2 rbook">
            <h4><%= book.title %></h4>
            <%= link_to user_book_path(current_user, book) do %>
              <%= image_tag book.image(:thumb), class: "thumbnail" %>
            <% end %>
          </div>
        <% end %>  
      </div> 
    </div> 
  </div>
<% else %>
  <div class="container" style="position:relative;">
    <h1 id="results-h">Resultados</h1>
  </div>
  <%= render 'show_results' %>
<% end %>

app/views/welcome/index.html.erb
<div id="background-image" style="background: url(http://eden.rutgers.edu/~emd156/555/images/21st%20cent%202.jpg) no-repeat center center; background-size: cover; -webkit-background-size: cover;-moz-background-size: cover; -o-background-size: cover;background-attachment: fixed;"></div> 
<div id="background-overlay"></div>

<%= render 'shared/alerts' %>

<div class="container home-content" style="position:relative;" >
  <h1 class="hidden-xs hidden-sm">Lee, Compra y sube tus propios libros con PickAppBook</h1>
</div>

<% if @books != [] %>
  <div class="container" style="padding-top:10px;">
    <h1 id="results-h"><span class="glyphicon glyphicon-star" style="margin-top:3px;"></span> Resultado</h1>
    <hr class="featurette-divider" style="position:relative;padding-top:55px;">
  </div>
  <%= render 'show_results' %>
<% else %>
  <% if @best_book != [] %>
    <div class="container" style="padding-top:10px;">
      <h1 id="results-h"><span class="glyphicon glyphicon-star" style="margin-top:3px;"></span> Libros más populares</h1>
      <hr class="featurette-divider" style="position:relative;padding-top:55px;">
    </div>
    <div id="results-frame" class="container" style="position:relative;">
      <div class="row">
        <% @best_book.each do |book| %> 
            <div class="book-result col-md-15 col-lg-15 col-sm-6 col-xs-6">
              <div class="result-container">
                <figure>
                  <%= link_to book[1][:link], target: "_blank" do %>
                    <%= image_tag book[1][:image], class: "thumbnail", size: '180x265' %>
                  <% end %>
                </figure>
                <div class="book-result-bottom">
                  <%= link_to book[1][:title], book[1][:link], class: "book-title", target: "_blank" %>
                </div>
              </div>
            </div>
        <% end %>
      </div>
  <% end %>
<% end %>