config/routes.rb
Rails.application.routes.draw do

  get 'googlebooks/show'

  get '/about' => 'annexes#about', as: :About
  get '/documentation' => 'annexes#documentation', as: :Documentation
  get '/contact' => 'annexes#contact', as: :Contact
  
  root 'welcome#index'
  get '/home' => 'welcome#home', as: :Home

  resources :password_resets, except: [:index, :destroy]
  resources :confirmations, only: :show
  resources :sessions, only: [:create, :destroy]
  
  resources :users, except: [:new, :show, :destroy, :edit, :index] do
    resources :books, except: [:index]
  end

  get '/singup' => 'users#new', as: :Singup
  get '/login' => 'sessions#new', as: :Login

  get 'users/:username' => 'users#show'
  put 'users/:username' => 'users#update'
  delete 'users/:username' => 'users#destroy'
  get 'users/:username/edit' => 'users#edit'
  
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user

  obfuscate_id

  validates :title, presence: true, on: :create
  validates :title, uniqueness: true

  has_attached_file :image,
    storage: :dropbox,
    styles: { medium: "300x300!", thumb: "100x100!", icon: "50x50!" },
    default_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSo8uPVFZTL8nxsBIPhyBw9DxZ0lbyS4hqMpQxQU4wYu0gaFDe34q-UhsHr",
    dropbox_credentials: Rails.root.join("#{Rails.root}/config/dropbox.yml"),
    dropbox_options: { path: proc { |style| "files/books/user_#{user_id}/#{id}/image/#{image.original_filename}" } },
    unique_filename: true 
  validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_attached_file :pdf,
    storage: :dropbox,
    dropbox_credentials: Rails.root.join("#{Rails.root}/config/dropbox.yml"),
    dropbox_options: { path: proc { |style| "files/books/user_#{user_id}/#{id}/pdf/#{pdf.original_filename}" } },
    unique_filename: true 
  validates_attachment_content_type :pdf, content_type: ["application/pdf"]
  validates_attachment :pdf, presence: true

  before_save :format_attributes

  def self.search(attrb, query)
    where("#{attrb} like ?", "%#{query}%") 
  end

  private
  def format_attributes
    self.title.downcase!
    self.authors.downcase!
    self.description.downcase!
    self.categories.downcase!
    self.publisher.downcase!
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :require_login, only: [:show]
  before_filter :require_login, only: [:edit, :update, :new, :create, :destroy]
  before_action :get_user, only: [:new, :create]
  before_action :get_book, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @book = @user.books.new
  end

  def edit
  end

  def update
    @book.assign_attributes(book_params)
    if @book.save
      redirect_to "/users/#{current_user.username}", notice: 'El libro ha sido actualizado'
    else
      render :edit
    end
  end

  def create
    @book = @user.books.new(book_params)
    if @book.save
      redirect_to :root, notice: 'El libro ha sido creado'
    else
      flash[:error] = 'No se ha podido crear el libro'
      render :new
    end
  end

  def destroy
    @book.destroy
    redirect_to :root
  end

  private

  def get_user
    @user = User.find(params[:user_id])
  end

  def book_params
    params.require(:book).permit(:image, :pdf, :title, :authors, :description, :categories, :isbn, :publisher, :published_date)
  end

  def get_book
    get_user
    @book = Book.find(params[:id])
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div id="background-image" style="background: url(http://p1.pichost.me/640/64/1889210.jpg) no-repeat center center; background-size: cover; -webkit-background-size: cover;-moz-background-size: cover; -o-background-size: cover;background-attachment: fixed;"></div> 
<div id="background-overlay"></div>

<div id="background-overlay"></div>
<div class="container">
  <h1>Edita tu libro</h1>
  <hr>
  <%= form_for [@user, @book], html: { multipart: true, class: "form-horizontal" } do |f| %>
    <div class="row">
       <div class="col-md-3">
        <div class="text-center">
          <%= image_tag @book.image.url(:thumb), class: "avatar img-circle" %>
          <h6>Sube una imagen...</h6>
          <%= f.file_field :image %>
          <h6>Sube el pdf...</h6>
          <%= f.file_field :pdf %>
        </div>
      </div>
      <div class="col-md-9 personal-info">
        <% if @book.errors.any? %>
          <div class="alert alert-info alert-dismissable">
            <a class="panel-close close" data-dismiss="alert">×</a> 
            <i class="fa fa-coffee"></i>
            <ul>
              <% for message in @book.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        
        <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Información del Libro</h3>

        <div class="form-group">
          <%= f.label 'Titulo', class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :title, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Autores", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :authors, class: "form-control", placeholder: 'separados por ,' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Descripcion", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_area :description, size: "19x10", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Categorias", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :categories, class: "form-control", placeholder: 'separados por ,' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "isbn", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :isbn, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Editorial", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :publisher, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Fecha de publicacion", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.date_select :published_date, start_year: 1800, end_year: Date.today.year, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-8">
            <%= f.submit "Editar Libro", class: 'btn btn-primary' %>
            <span></span>
            <%= link_to "Cancelar", "/users/#{@user.username}", class: 'btn btn-default' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<div id="background-image" style="background: url(http://p1.pichost.me/640/64/1889210.jpg) no-repeat center center; background-size: cover; -webkit-background-size: cover;-moz-background-size: cover; -o-background-size: cover;background-attachment: fixed;"></div> 
<div id="background-overlay"></div>

<div id="background-overlay"></div>
<div class="container">
  <h1>Crea tu libro</h1>
  <hr>
  <%= form_for [@user, @book], html: { multipart: true, class: "form-horizontal" } do |f| %>
    <div class="row">
       <div class="col-md-3">
        <div class="text-center">
          <h6>Sube una imagen...</h6>
          <%= f.file_field :image %>
          <h6>Sube el pdf...</h6>
          <%= f.file_field :pdf %>
        </div>
      </div>
      <div class="col-md-9 personal-info">
        <% if @book.errors.any? %>
          <div class="alert alert-info alert-dismissable">
            <a class="panel-close close" data-dismiss="alert">×</a> 
            <i class="fa fa-coffee"></i>
            <ul>
              <% for message in @book.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        
        <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Información del Libro</h3>

        <div class="form-group">
          <%= f.label 'Titulo', class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :title, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Autores", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :authors, class: "form-control", placeholder: 'separados por ,' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Descripcion", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_area :description, size: "19x10", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Categorias", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :categories, class: "form-control", placeholder: 'separados por ,' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "isbn", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :isbn, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Editorial", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.text_field :publisher, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Fecha de publicacion", class: "col-lg-3 control-label" %>
          <div class="col-lg-8">
            <%= f.date_select :published_date, start_year: 1800, end_year: Date.today.year, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-8">
            <%= f.submit "Crear Libro", class: 'btn btn-primary' %>
            <span></span>
            <%= link_to "Cancelar", "/users/#{@user.username}", class: 'btn btn-default' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div id="background-image" style="background: url(http://p1.pichost.me/640/64/1889210.jpg) no-repeat center center; background-size: cover; -webkit-background-size: cover;-moz-background-size: cover; -o-background-size: cover;background-attachment: fixed;"></div>
<div id="background-overlay"></div>

<div class="container" style="margin-top:15px;">
  <div class="row">
    <div id="mobile-book-info" class="visible-xs col-xs-12"> 
      <h1><%= @book.title %></h1> 
      <h2><%= @book.published_date %></h2> 
      <h2><%= @book.categories.gsub(',',' /') %></h2> 
    </div>

    <div id="book-poster" class="col-lg-3 col-md-5 col-sm-5 col-xs-12">
      <% if @book.image %>
        <%= image_tag @book.image(:thumb), class: "img-responsive thumbnail", size: "200x285" %>
      <% else %>
        <%= image_tag 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSo8uPVFZTL8nxsBIPhyBw9DxZ0lbyS4hqMpQxQU4wYu0gaFDe34q-UhsHr', class: "img-responsive thumbnail", size: "200x285" %>
      <% end %>
      <% if current_user == @user %>
        <%= link_to 'Editar Libro', edit_user_book_path(@user, @book), style: 'margin-left:35px;', class: "btn btn-success" %>
        <%= link_to 'Eliminar Libro', user_book_path(@user, @book), style: 'margin-left:35px;', class: "btn btn-danger", method: :delete, data: { confirm: "Estas Seguro?" } %>
      <% else %>
        <% if logged_in? %>     
          <%= link_to 'Descargar Libro', @book.pdf.url, style: 'margin-left:35px;', class: "btn btn-primary"%>
        <% end %>  
        <%= link_to 'Propietario', "/users/#{@book.user.username}", style: 'margin-left:35px;', class: "btn btn-success" %>
      <% end %>
    </div>

    <div id="book-info" class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
      <div class="hidden-xs">
        <h1><%= @book.title %></h1> 
        <h2><%= @book.published_date %></h2> 
        <h2><%= @book.categories.gsub(',',' /') %></h2>  
      </div>
      <p>
        <em class="pull-left">Disponible en: &nbsp;</em>
        <a>e-Book</a>
      </p>
      <div class="bottom-info">
        <div class="rating-row">
          <span class="icon glyphicon glyphicon-user blue"></span>
          <span><%= @book.authors %></span>
        </div class="text">
        <div class="rating-row">
          <span class="icon glyphicon glyphicon-book blue"></span>
          <span class="text"><%= @book.publisher %></span>
        </div>
        <div class="rating-row">
          <span class="icon glyphicon glyphicon-barcode blue"></span>
          <span class="text"><%= @book.isbn %></span>
        </div>
      </div>
    </div>
    
    <div id="synopsis" class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
      <h3>Sinopsis</h3>
      <p><%= @book.description %></p>
    </div>
  </div>
</div>