config/routes.rb
Rails.application.routes.draw do

  get 'googlebooks/show'

  get '/about' => 'annexes#about', as: :About
  get '/documentation' => 'annexes#documentation', as: :Documentation
  get '/contact' => 'annexes#contact', as: :Contact
  
  root 'welcome#index'
  get '/home' => 'welcome#home', as: :Home

  resources :password_resets, except: [:index, :destroy]
  resources :confirmations, only: :show
  resources :sessions, only: [:create, :destroy]
  
  resources :users, except: [:new, :show, :destroy, :edit, :index] do
    resources :books, except: [:index]
  end

  get '/singup' => 'users#new', as: :Singup
  get '/login' => 'sessions#new', as: :Login

  get 'users/:username' => 'users#show'
  put 'users/:username' => 'users#update'
  delete 'users/:username' => 'users#destroy'
  get 'users/:username/edit' => 'users#edit'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Libros</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  </head>

  <body>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-63191418-1', 'auto');
      ga('send', 'pageview');

    </script>

    <header class="navbar navbar-default navbar-fixed-top navbar-inverse">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <% if current_user %>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#search-book-div">
              <span class="sr-only">Toggle navigation</span>
              <span class="glyphicon glyphicon-search white"></span>
            </button>
            <a class="navbar-brand" href=<%= '/home' %>><img alt="Brand" src="http://icons.iconarchive.com/icons/double-j-design/ravenna-3d/256/Book-icon.png" height="30" style="margin-top:-4px;"></a>
          <% else %>
            <a class="navbar-brand" href=<%= root_path %>><img alt="Brand" src="http://icons.iconarchive.com/icons/double-j-design/ravenna-3d/256/Book-icon.png" height="30" style="margin-top:-4px;"></a>
          <% end %>
          
        </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li><a href=<%= '/home' %>>Inicio <span class="sr-only">(current)</span></a></li>
            <% else %>
              <li><a href=<%= root_path %>>Inicio <span class="sr-only">(current)</span></a></li>
            <% end %>
          </ul>

          <%= form_tag(current_user ? :Home : :root, :method => "get", id: "search-form", class: "navbar-form navbar-left") do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], placeholder: "Busca un libro", class: "form-control", style: "width:290px;" %>
            </div>
            <%= submit_tag "Buscar", :name => nil, class: 'btn btn-primary' %>
          <% end %>

          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li></li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false"><%= image_tag current_user.avatar.url(:icon), size: '20x20', class: "avatar img-circle" %>&nbsp;<%= current_user.username %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Ver Perfil', "/users/#{current_user.username}" %></li>
                  <li><%= link_to 'Editar Perfil', "/users/#{current_user.username}/edit" %></li>
                  <li><%= link_to 'Crear libro', new_user_book_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Cerrar sesión', session_path(current_user), method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Registrate', :Singup %></li>
              <li><%= link_to 'Inicia Sesión', :Login %></li>
            <% end %> 
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </header>
    
    <%= yield %>

    <div id="footer">
      <footer class="footer-distributed">
        <div class="container">
          <div class="footer-right">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="https://github.com/2l3x2nd3r/software-design-project" target="_blank"><i class="fa fa-github"></i></a>
          </div>
          <div class="footer-left">
            <p class="footer-links">
              <%= link_to 'Inicio', :root %>
              ·
              <%= link_to 'Documentación', :Documentation %>
              ·
              <%= link_to 'Acerca', :About %>
              ·
              <%= link_to 'Contáctanos', :Contact %>
            </p>
            <p>PickAppBook &copy; 2015</p>
          </div>
        </div>
      </footer>
    </div>
  
  </body>
</html>